name: 米游社自动签到

# 触发条件：每天UTC时间0点30分执行（北京时间8点30分）
on:
  schedule:
    - cron: '30 0 * * *'
  # 允许手动触发
  workflow_dispatch:

jobs:
  sign-in:
    runs-on: ubuntu-latest
    
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
      
      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests  # 签到脚本通常需要requests库
      
      - name: 执行签到脚本
        env:
          # 从GitHub Secrets中获取Cookie信息
          GENSHIN_COOKIES: ${{ secrets.GENSHIN_COOKIES }}
        run: |
          # 假设仓库中有签到脚本sign_in.py
          python sign_in.py
      
      - name: 输出签到结果
        if: always()
        run: echo "签到任务已完成，查看上方日志获取详情"
